<a href="https://colab.research.google.com/github/csoren66/Machine-Learning/blob/main/2_Linear_regression_Multiple_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv('/content/homeprices.csv')

In [3]:
df

area  badroom  age    price
0  2600      3.0   20   550000
1  3000      4.0   15  5650000
2  3200      NaN   18  6100000
3  3600      3.0   30  5950000
4  4000      5.0    8  7600000

In [7]:
import math
median_badroom = math.floor(df.badroom.median())
median_badroom

3

In [9]:
df.badroom=df.badroom.fillna(median_badroom)
df

area  badroom  age    price
0  2600      3.0   20   550000
1  3000      4.0   15  5650000
2  3200      3.0   18  6100000
3  3600      3.0   30  5950000
4  4000      5.0    8  7600000

In [10]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'badroom', 'age']], df.price)

LinearRegression()

In [11]:
reg.coef_

array([   4590., -681000.,  -93000.])

In [12]:
reg.intercept_

-5741000.000000004

In [16]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([2266000.00000001])

In [17]:
4590.*3000+-681000.*3+-93000.*40+-5741000.000000004

2265999.9999999963

In [18]:
reg.predict([[2000,4,30]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([-2074999.99999999])